# Generated by Django 5.2.5 on 2025-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_listing_name_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pictures',
            field=models.ImageField(upload_to='listing_images/'),
        ),
    ]
