# Generated by Django 4.2.9 on 2025-10-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Untitled Order', max_length=300),
            preserve_default=False,
        ),
    ]
