# Generated by Django 5.2.5 on 2025-09-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='listing',
        ),
    ]
