# Generated by Django 5.2.5 on 2025-09-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_product_order_listing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='user_or_tem_user_is_filled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='temp_user',
        ),
    ]
