# Generated by Django 5.2.3 on 2025-07-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersellers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersellers',
            old_name='company_name',
            new_name='username',
        ),
    ]
