# Generated by Django 5.2.3 on 2025-07-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_company_name_usersellers_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSellers',
        ),
    ]
