# Generated by Django 5.2.7 on 2025-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_follows_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
    ]
