# Generated by Django 5.2.5 on 2025-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_usersellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_company_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
