# Generated by Django 5.2.5 on 2025-09-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_user_or_tem_user_is_filled_and_more'),
        ('user', '0007_tempuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
